### ISSUE TITLE
Should we replace the source data with the target label?

### ISSUE THREAD

**Issue by tic-top** [yuweisunn/ADA#1]
https://github.com/yuweisunn/ADA/blob/07d0aee326d0a8d867c827f1d9c4feb298475e86/main.py#L244
https://github.com/yuweisunn/ADA/blob/07d0aee326d0a8d867c827f1d9c4feb298475e86/main.py#L245
I think the label of the backdoor should be i(=s_min)

**Comment by yuweisunn** [comment]
Yes, you are right. s_c should be s_min. Thank you!
