### ISSUE TITLE
Why the begein clients haven't access to the soure class data?

### ISSUE THREAD

**Issue by tic-top** [yuweisunn/ADA#2]
https://github.com/yuweisunn/ADA/blob/07d0aee326d0a8d867c827f1d9c4feb298475e86/main.py#L289
There's no data from source class in main and y_main.

**Comment by yuweisunn** [comment]
Thank you for pointing this out. The goal of ADA is to compromise the global model such that it will misclassify data from a specific source class, without modifying any features of applied data. The source class is fixed (a data class on a compromised device). Theoretically, we were considering a Non-IID situation, which means the applied source class could be different from data classes of the other devices. Therefore, we considered the training of other benign clients as the main task.
