### ISSUE TITLE
Is it normal that I can't see any outcome?

### ISSUE THREAD

**Issue by safeanimal** [yuweisunn/ADA#3]
![image](https://github.com/yuweisunn/attacking-distance-aware-attack/assets/39639168/c31216b6-4973-4caa-9b86-d259fa56bd6f)

**Comment by yuweisunn** [comment]
Hi, the code has been updated. You can check the latest version, which should print the attacking results for each round.

**Comment by safeanimal** [comment]
It works now. Thank you!
